### ISSUE TITLE
Fetching playlists error

### ISSUE THREAD

**Issue by StatelessOddity** [syhlx/plugin.video.piped#2]
Hey, I wanted to test this out, so I logged in to piped.kavin.rocks and tried to grab the content I saved there. However, I'm getting a blank error in the GUI. I've checked addons settings XML file just to be sure that the login data is correct - it is. This is the error that I'm getting in the logs:
```

2024-03-16 02:09:56.019 T:1615    error <general>: GetDirectory - Error getting plugin://plugin.video.piped/subscriptions
2024-03-16 02:09:56.027 T:848     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.piped/subscriptions) failed
2024-03-16 02:09:58.416 T:1625    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: string indices must be integers, not 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.piped/default.py", line 8, in <module>
                                                       router(sys.argv)
                                                     File "/storage/.kodi/addons/plugin.video.piped/lib/sections.py", line 285, in router
                                                       globals()[route](**routes[route])
                                                     File "/storage/.kodi/addons/plugin.video.piped/lib/sections.py", line 169, in playlists
                                                       list_playlists(get(f'{instance}/user/playlists', headers={'Authorization': auth_token}).json())
                                                     File "/storage/.kodi/addons/plugin.video.piped/lib/sections.py", line 143, in list_playlists
                                                       info += f"{addon.getLocalizedString(30018)}: {playlist['videos']}"
                                                                                                     ~~~~~~~~^^^^^^^^^^
                                                   TypeError: string indices must be integers, not 'str'
                                                   -->End of Python script error report<--
```

Also, it is impossible to browse this addon via widget creators. I wanted to create a widget with trenging videos, but Pipes is not showing in Video addons like any othe addon while choosing path for the widget.

Could you please help me? Piped is much better way of watching YouTube than the default application.

**Comment by syhlx** [comment]
I added a quick check for the missing information in playlists provided by the instance.

Can you try again with the new changes? -> [Latest version](https://github.com/syhlx/plugin.video.piped/archive/refs/heads/main.zip)
You can then install as a ZIP in Kodi.

As for your querstion about adding to a widget: you should be able to, but, weirdly, the plugin was listed as service addon in the Official Kodi Repository instead of a video addon.
I'll check with Kodi's maintainers for the next release.

**Comment by syhlx** [comment]
I think it was due to an expired session.

I added a "re-login" when this happens.

Can you try again with the new changes? -> [Latest version](https://github.com/syhlx/plugin.video.piped/archive/refs/heads/main.zip)
Then, installing it as a ZIP in Kodi.

**Comment by StatelessOddity** [comment]
It works! Thank you for your work.
